const student = {
  id: "ES-2026-1042",
  firstName: "Aliya",
  fullName: "Aliya",
  class: "Grade 11 - Commerce",
  campus: "EuroSchool HSR",
  attendance: 94,
  profileImage: "A",
  nextClass: { subject: "Accountancy", time: "10:30 AM", room: "Room 302" },
  marks: [
    { subject: "Accountancy", score: 92, total: 100, grade: "A1", trend: "+4" },
    { subject: "Economics", score: 88, total: 100, grade: "A2", trend: "+2" },
    {
      subject: "Business Studies",
      score: 84,
      total: 100,
      grade: "A2",
      trend: "+1",
    },
    {
      subject: "Applied Maths",
      score: 79,
      total: 100,
      grade: "B1",
      trend: "+3",
    },
    { subject: "English", score: 86, total: 100, grade: "A2", trend: "+2" },
  ],
};

const notices = [
  {
    id: 1,
    title: "Uniform Schedule",
    teacher: "Manju Kasana",
    initials: "MK",
    date: "22 Jun",
    category: "Circular",
    action: "Follow uniform schedule from AY 2026-27",
    body: "Dear students, the revised weekday uniform schedule will apply from academic year 2026-27. Please review the attached circular and come dressed in the appropriate uniform each day.",
    attachment: "Uniform Schedule.pdf",
    unread: true,
  },
  {
    id: 2,
    title: "Subject Confirmation Form",
    teacher: "Manju Kasana",
    initials: "MK",
    date: "17 Jun",
    category: "Academic",
    action: "Sign and return form to class teacher by Friday",
    body: "The subject confirmation form has been shared with all Grade 11 students. Please verify your selected subjects, get a parent signature and return it to your class teacher.",
    attachment: "Subject Confirmation.pdf",
    unread: true,
  },
  {
    id: 3,
    title: "PTM Scheduled",
    teacher: "Admin",
    initials: "AD",
    date: "24 Jun",
    category: "Important",
    action: "Inform parents — PTM on July 10th",
    body: "The parent-teacher meeting for Grade 11 is scheduled for 10 July. Individual time slots will be shared shortly through Argus.",
    attachment: "PTM Notice.pdf",
    unread: true,
  },
  {
    id: 4,
    title: "Exam Schedule Released",
    teacher: "Admin",
    initials: "AD",
    date: "24 Jun",
    category: "Exams",
    action: "Review the examination timetable before July 7th",
    body: "The term examination schedule is now available. Examinations begin on 7 July. Students should report 30 minutes before the scheduled start time.",
    attachment: "Exam Schedule.pdf",
    unread: false,
  },
];

const notes = [
  {
    id: 1,
    subject: "Economics",
    title: "Demand and Supply",
    teacher: "Mr. Rajan",
    date: "23 Jun",
    color: "#2f9e88",
    bookmarked: false,
  },
  {
    id: 2,
    subject: "Accountancy",
    title: "Accounting Equation",
    teacher: "Mrs. Priya",
    date: "22 Jun",
    color: "#5b5fc7",
    bookmarked: true,
  },
  {
    id: 3,
    subject: "Applied Maths",
    title: "Compound Interest",
    teacher: "Mr. Suresh",
    date: "21 Jun",
    color: "#e35d6a",
    bookmarked: false,
  },
  {
    id: 4,
    subject: "Business Studies",
    title: "Business Services",
    teacher: "Mrs. Anita",
    date: "20 Jun",
    color: "#e39a3b",
    bookmarked: false,
  },
  {
    id: 5,
    subject: "English",
    title: "Article Writing",
    teacher: "Ms. Kavita",
    date: "19 Jun",
    color: "#4c8dd9",
    bookmarked: false,
  },
  {
    id: 6,
    subject: "Economics",
    title: "Consumer Equilibrium",
    teacher: "Mr. Rajan",
    date: "18 Jun",
    color: "#2f9e88",
    bookmarked: true,
  },
  {
    id: 7,
    subject: "Accountancy",
    title: "Journal Entries",
    teacher: "Mrs. Priya",
    date: "17 Jun",
    color: "#5b5fc7",
    bookmarked: false,
  },
  {
    id: 8,
    subject: "Business Studies",
    title: "Emerging Modes of Business",
    teacher: "Mrs. Anita",
    date: "16 Jun",
    color: "#e39a3b",
    bookmarked: false,
  },
];

const tasks = [
  {
    id: 1,
    title: "Accounting Equation Worksheet",
    subject: "Accountancy",
    type: "Worksheet",
    due: "26 Jun",
    status: "Pending",
    color: "#5b5fc7",
  },
  {
    id: 2,
    title: "Business Services Project",
    subject: "Business Studies",
    type: "Project",
    due: "27 Jun",
    status: "Pending",
    color: "#e39a3b",
  },
  {
    id: 3,
    title: "Compound Interest Problems",
    subject: "Applied Maths",
    type: "Worksheet",
    due: "30 Jun",
    status: "Pending",
    color: "#e35d6a",
  },
  {
    id: 4,
    title: "Demand Analysis Essay",
    subject: "Economics",
    type: "Project",
    due: "3 Jul",
    status: "Pending",
    color: "#2f9e88",
  },
];

const events = [
  { date: "2026-06-05", title: "Environment Day", type: "event" },
  { date: "2026-06-12", title: "Senate Elections", type: "event" },
  {
    date: "2026-06-19",
    title: "Radio Jockey Interhouse Competition",
    type: "event",
  },
  { date: "2026-06-20", title: "Orion Launch", type: "event" },
  { date: "2026-06-22", title: "Music and Yoga Day", type: "event" },
  { date: "2026-07-03", title: "Sports Day", type: "sports" },
  { date: "2026-07-07", title: "Exams Begin", type: "exam" },
  { date: "2026-07-10", title: "PTM", type: "ptm" },
];

const holidays = events
  .filter((event) => event.type !== "event")
  .map((event, id) => ({ id: id + 1, name: event.title, date: event.date }));
const athenaBrief = [
  "Accounting worksheet due tomorrow",
  "Mr. Rajan posted Economics notes today",
  "Bring ₹200 for art supplies by Wednesday",
];

module.exports = {
  student,
  notices,
  notes,
  tasks,
  events,
  holidays,
  athenaBrief,
};
